SET NAMES UTF8;
CREATE DATABASE YBS CHARSET=UTF8;
USE YBS;
CREATE TABLE songInfo(
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR ,
	artist VARCHAR,
	songSheet INT,
	picture VARCHAR,
	lrc VARCHAR,
	url VARCHAR,
	style VARCHAR,
	hot int,
	FOREIGN KEY(songSheet) REFERENCES sheetInfo(id)
	
);

CREATE TABLE sheetInfo(
	id INT PRIMARY KEY AUTO_INCREMENT,
	songSheetName VARCHAR ,
		incroduce VARCHAR
		
);
